/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mNnNUVjLF4a
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client';
import { Button } from "@/components/ui/button"
import {createClient} from "@/lib/supabase/client"

export function GoogleLoginButton({ token}) {

  const supabase = createClient()
  const signInWithGoogle = async () => {
    console.log("signing in with google")
    const {error, data} = await supabase.auth.signInWithOAuth({
      provider: 'google',
      options: {
        redirectTo: `https://gorgeous-blancmange-ad9e07.netlify.app/auth/callback${token ? '?token='  + token : ''}`,
        queryParams: {
          access_type: 'offline',
          prompt: 'consent',
        },
      }
    })
    console.log("google sign in error", error)
    console.log("google sign in data", data)

  }

  return (
    <Button onClick={() => signInWithGoogle()} className="w-full inline-flex items-center justify-center rounded-md px-4 py-2 text-sm font-medium bg-primary text-secondary  ">
      <ChromeIcon className="mr-2 h-5 w-5" />
      Sign in with Google
    </Button>
  )
}

function ChromeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  )
}
